### ISSUE TITLE
An error occurs while using recommended version of scikit-allel (0.20.3)

### ISSUE THREAD

**Issue by dukelheit** [Gregor-Mendel-Institute/SNPmatch#16]
After installing snpmatch using the recommended conda enviroment i had tried running it with the next code:

`snpmatch inbred -d all_chromosomes_binary.hdf5 -e all_chromosomes_binary.acc.hdf5 -i 701_501.filter.vcf \-o output_snpmatch`

getting this error:

2020-07-16 09:50:20,704 - root - ERROR - 'module' object has no attribute 'read_vcf'
Traceback (most recent call last):
  File "/home/franco/anaconda3/envs/snpmatch/lib/python2.7/site-packages/snpmatch/__init__.py", line 175, in main
    args['func'](args)
  File "/home/franco/anaconda3/envs/snpmatch/lib/python2.7/site-packages/snpmatch/__init__.py", line 120, in snpmatch_inbred
    snpmatch.potatoGenotyper(args)
  File "/home/franco/anaconda3/envs/snpmatch/lib/python2.7/site-packages/snpmatch/core/snpmatch.py", line 229, in potatoGenotyper
    inputs = parsers.ParseInputs(inFile = args['inFile'], logDebug = args['logDebug'])
  File "/home/franco/anaconda3/envs/snpmatch/lib/python2.7/site-packages/snpmatch/core/parsers.py", line 66, in __init__
    (snpCHR, snpPOS, snpGT, snpWEI, DPmean) = self.read_vcf(inFile, logDebug)
  File "/home/franco/anaconda3/envs/snpmatch/lib/python2.7/site-packages/snpmatch/core/parsers.py", line 131, in read_vcf
    vcf = allel.read_vcf(inFile, samples = [0], fields = '*')
AttributeError: 'module' object has no attribute 'read_vcf'

i have solved this problem installing a more recent version from scikit-allel (v1.1.0), maybe the enviroment file can be edited to change this?
Regards

**Comment by rbpisupati** [comment]
Thank you! I have pushed the required changes.
