### ISSUE TITLE
SNPmatch error

### ISSUE THREAD

**Issue by wyim-pgl** [Gregor-Mendel-Institute/SNPmatch#8]
Dear Rahul,

Hello,

I tried to use SNPmatch but it generated error.
Can you please take a look?

``
/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py:52: RuntimeWarning: invalid value encountered in less
  NumAmb = np.where(likeliHoodRatio < snpmatch.lr_thres)[0]
2018-05-10 14:56:04,744 - root - ERROR - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/__init__.py", line 163, in main
    args['func'](args)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/__init__.py", line 105, in snpmatch_cross
    csmatch.potatoCrossIdentifier(args)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 232, in potatoCrossIdentifier
    crossIdentifier(args['binLen'],snpCHR, snpPOS, snpWEI, DPmean, GenotypeData, GenotypeData_acc, args['outFile'])
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 187, in crossIdentifier
    (ScoreList, NumInfoSites, NumMatSNPs) = crossWindower(binLen, snpCHR, snpPOS, snpWEI, DPmean, GenotypeData, outFile)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 101, in crossWindower
    writeBinData(out_file, i, GenotypeData, ScoreList, NumInfoSites)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 50, in writeBinData
    (likeliScore, likeliHoodRatio) = snpmatch.calculate_likelihoods(ScoreList, NumInfoSites)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/snpmatch.py", line 41, in calculate_likelihoods
    LikeLiHoods = [likeliTest(NumInfoSites[i], int(ScoreList[i])) for i in range(num_lines)]
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/snpmatch.py", line 27, in likeliTest
    if n > 0 and n != y and y > 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by rbpisupati** [comment]
Hi @ascendo , 

Can you provide a sample file on which you are running SNPmatch? Is this the error on the AraGeno or standalone version?


Rahul

**Comment by wyim-pgl** [comment]
I use pip version and it doesn't work.
But with git cone version 2.0, it worked.

AraGeno is web version that i use.


By the way, can you tell me about SNPmatch output?

Thanks.

Won

____________________

Won Cheol Yim

Research Scientist

+1 775 229 0453 | wyim@unr.edu | http://www.plantbioinformatics.org/

MS330/Department of Biochemistry & Molecular Biology
1664 N. Virginia Street, Reno NV
University of Nevada - Reno
89557

________________________________

**Comment by rbpisupati** [comment]
Hi Won,

We will update version on AraGeno soon and with a detailed output in the README file.

Briefly, SNPmatch output contains accession number, number of SNPs that were matched compared to total SNPs and likelihood scores. Json file generated contains only matched accessions with 95% confidence based on likelihood ratio test.


Rahul

**Comment by rbpisupati** [comment]
@timeu can you update AraGeno to version 2.0 of SNPmatch..? Thanks
