### ISSUE TITLE
SNPmatch error

### ISSUE THREAD

**Issue by wyim-pgl** [Gregor-Mendel-Institute/SNPmatch#9]
Dear Rahul,

Hello,

I tried to use SNPmatch but it generated error.
Can you please take a look?

Can you  also check the Arageno?

http://tools.1001genomes.org/strain_id/#progress/116f3740-f33c-4268-adeb-b9a932ebb7fc

Thanks !

```
/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py:52: RuntimeWarning: invalid value encountered in less
  NumAmb = np.where(likeliHoodRatio < snpmatch.lr_thres)[0]
2018-05-10 14:56:04,744 - root - ERROR - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/__init__.py", line 163, in main
    args['func'](args)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/__init__.py", line 105, in snpmatch_cross
    csmatch.potatoCrossIdentifier(args)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 232, in potatoCrossIdentifier
    crossIdentifier(args['binLen'],snpCHR, snpPOS, snpWEI, DPmean, GenotypeData, GenotypeData_acc, args['outFile'])
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 187, in crossIdentifier
    (ScoreList, NumInfoSites, NumMatSNPs) = crossWindower(binLen, snpCHR, snpPOS, snpWEI, DPmean, GenotypeData, outFile)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 101, in crossWindower
    writeBinData(out_file, i, GenotypeData, ScoreList, NumInfoSites)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/csmatch.py", line 50, in writeBinData
    (likeliScore, likeliHoodRatio) = snpmatch.calculate_likelihoods(ScoreList, NumInfoSites)
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/snpmatch.py", line 41, in calculate_likelihoods
    LikeLiHoods = [likeliTest(NumInfoSites[i], int(ScoreList[i])) for i in range(num_lines)]
  File "/mnt/d/scratch/bin/python_default/local/lib/python2.7/site-packages/snpmatch/core/snpmatch.py", line 27, in likeliTest
    if n > 0 and n != y and y > 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by rbpisupati** [comment]
Resolved in version 2.0.0
